### PR TITLE
48 separator, list items, text styling, image sizes, spacing, tablet layout

### LINKED ISSUE #48: durysta may be right for you section
image

- [x] Font styling in the doc
- [x] alignment in css
- [x] grey background for Ask your doctor section and offer information
- [x] list items have a bit more separation (spacing) on live on all resolutions
- [x] The Ask Your Doctor section / grey box has some differences in the image and title area: image is larger, text column is narrower on live on tablet and desktop
- [x] Image is a bit larger on live on tablet landscape
- [x] layout inconsistencies coupled with font sizing differences on tablet portrait / mobile landscape
- [x] Image size and some spacing differences on mobile portrait
- [x] other styling observations

### LINKED ISSUE #58: side by side columns blocks on tablet
* On tablet portrait the layout shifts to 2 columns on live, while on local it still shows 1 column:
>   image
>   image

### PR DESCRIPTION
**Pull request by rootpea**
Fix #48
Fix #58 

Test URLs:
- Before: https://main--durysta--hlxsites.hlx.page
- After: https://48-separator--durysta--hlxsites.hlx.page/drafts/rootpea/

### CODE REVIEW

**Comment by dragoss-nc** [comment]
Hello,

A couple of differences:
- The list items have a bit more separation (spacing) on live (right) on all resolutions
image
- The Ask Your Doctor section / grey box has some differences in the image and title area: image is larger, text column is narrower on live (right) on tablet and desktop
image
- Image is a bit larger on live (right) on tablet landscape
image
- There are layout inconsistencies coupled with font sizing differences on tablet portrait / mobile landscape
image
- Image size and some spacing differences on mobile portrait
image

**Comment by rootpea** [comment]
> Hello,
> 
> A couple of differences:
> 
> * The list items have a bit more separation (spacing) on live (right) on all resolutions
>   image
> * The Ask Your Doctor section / grey box has some differences in the image and title area: image is larger, text column is narrower on live (right) on tablet and desktop
>   image
> * Image is a bit larger on live (right) on tablet landscape
>   image
> * There are layout inconsistencies coupled with font sizing differences on tablet portrait / mobile landscape
>   image
> * Image size and some spacing differences on mobile portrait
>   image

fixed all of these, thanks

**Comment by rootpea** [comment]
@dragoss-nc, @QuentinVecchio I applied the requested changes, could you please review

**Review by dragoss-nc — APPROVED** [review]
Looking good

**Pull request merged**
